export let recipes = [
  {
    name: "Spaghetti Carbonara",
    ingredients: [
      "spaghetti",
      "pancetta",
      "egg yolks",
      "parmesan cheese",
      "black pepper",
    ],
    processToPrepare: [
      "Cook spaghetti according to package instructions.",
      "In a skillet, cook pancetta until crispy.",
      "Whisk together egg yolks, parmesan cheese, and black pepper in a bowl.",
      "Combine drained spaghetti with pancetta in the skillet.",
      "Remove from heat and quickly stir in egg mixture until creamy.",
      "Serve immediately.",
    ],
    cuisine: "Italian",
    preparationTime: "30 minutes",
    dietaryRestrictions: ["Contains dairy", "Contains eggs", "Contains pork"],
    description:
      "A classic Italian pasta dish featuring creamy eggs, crispy pancetta, and parmesan cheese. Simple yet indulgent, it's a beloved comfort food worldwide.",
    rating: 4,
    foodId : "food1",
    addedToFav : false,

  },
  {
    name: "Chicken Tikka Masala",
    ingredients: [
      "chicken thighs",
      "yogurt",
      "tomato sauce",
      "cream",
      "spices (garam masala, cumin, coriander, paprika)",
    ],
    processToPrepare: [
      "Marinate chicken thighs in yogurt and spices for 1 hour.",
      "Grill or bake chicken until cooked through.",
      "Simmer tomato sauce with cream and additional spices.",
      "Add cooked chicken to the sauce and simmer for another 10 minutes.",
      "Serve with rice or naan.",
    ],
    cuisine: "Indian",
    preparationTime: "1 hour 30 minutes",
    dietaryRestrictions: ["Contains dairy"],
    description:
      "A popular Indian dish featuring tender chicken in a rich, creamy tomato-based sauce. Aromatic spices create a complex flavor profile.",
    rating: 5,
    foodId : "food2",
    addedToFav : false,

  },
  {
    name: "Caesar Salad",
    ingredients: [
      "romaine lettuce",
      "croutons",
      "parmesan cheese",
      "Caesar dressing",
      "lemon juice",
      "olive oil",
      "anchovy paste",
    ],
    processToPrepare: [
      "Toss torn romaine lettuce with Caesar dressing in a bowl.",
      "Sprinkle with croutons and shaved parmesan cheese.",
      "Whisk together lemon juice, olive oil, and anchovy paste for dressing.",
      "Drizzle dressing over salad just before serving.",
    ],
    cuisine: "Italian-American",
    preparationTime: "15 minutes",
    dietaryRestrictions: ["Contains dairy", "Contains fish"],
    description:
      "A classic salad of crisp romaine lettuce, crunchy croutons, and tangy Caesar dressing. The perfect balance of textures and flavors.",
    rating: 4,
    foodId : "food3",
    addedToFav : false,

  },
  {
    name: "Beef Tacos",
    ingredients: [
      "ground beef",
      "taco seasoning",
      "tortillas",
      "lettuce",
      "tomatoes",
      "cheese",
      "sour cream",
    ],
    processToPrepare: [
      "Cook ground beef with taco seasoning until browned and cooked through.",
      "Warm tortillas in a skillet or microwave.",
      "Assemble tacos with beef, lettuce, tomatoes, cheese, and sour cream.",
      "Serve immediately.",
    ],
    cuisine: "Mexican",
    preparationTime: "25 minutes",
    dietaryRestrictions: ["Contains dairy", "Contains beef"],
    description:
      "A Mexican-inspired favorite featuring seasoned ground beef in soft tortillas with fresh toppings. Customizable and perfect for casual dining.",
    rating: 5,
    foodId : "food4",
    addedToFav : false,
  },
  {
    name: "Chocolate Chip Cookies",
    ingredients: [
      "flour",
      "butter",
      "sugar",
      "brown sugar",
      "eggs",
      "vanilla extract",
      "chocolate chips",
      "baking soda",
    ],
    processToPrepare: [
      "Cream together butter, sugar, and brown sugar until light and fluffy.",
      "Beat in eggs and vanilla extract.",
      "Mix in flour and baking soda until combined.",
      "Stir in chocolate chips.",
      "Drop spoonfuls of dough onto baking sheets.",
      "Bake at 350°F (175°C) for 10-12 minutes until golden brown.",
      "Cool on wire racks.",
    ],
    cuisine: "American",
    preparationTime: "30 minutes",
    dietaryRestrictions: ["Contains dairy", "Contains eggs"],
    description:
      "Classic American cookies with a soft, chewy texture and gooey chocolate chips. A timeless treat loved by all ages.",
    rating: 4,
    foodId : "food5",
    addedToFav : false,
  },
  {
    name: "Caprese Salad",
    ingredients: [
      "tomatoes",
      "fresh mozzarella cheese",
      "basil leaves",
      "balsamic vinegar",
      "olive oil",
      "salt",
      "pepper",
    ],
    processToPrepare: [
      "Slice tomatoes and fresh mozzarella cheese into rounds.",
      "Arrange tomato and mozzarella slices on a plate.",
      "Tuck basil leaves between slices.",
      "Drizzle with balsamic vinegar and olive oil.",
      "Season with salt and pepper.",
      "Serve immediately.",
    ],
    cuisine: "Italian",
    preparationTime: "10 minutes",
    dietaryRestrictions: ["Contains dairy", "Vegetarian"],
    description:
      "A simple Italian salad showcasing fresh mozzarella, ripe tomatoes, and fragrant basil. Light, refreshing, and bursting with summer flavors.",
    rating: 5,
    addedToFav : false
  },
  {
    name: "Beef Stir Fry",
    ingredients: [
      "beef sirloin",
      "soy sauce",
      "ginger",
      "garlic",
      "vegetables (bell peppers, broccoli, carrots)",
      "sesame oil",
    ],
    processToPrepare: [
      "Slice beef thinly and marinate in soy sauce, ginger, and garlic.",
      "Stir fry beef in sesame oil until browned.",
      "Add vegetables and stir fry until tender-crisp.",
      "Serve hot with rice or noodles.",
    ],
    cuisine: "Asian",
    preparationTime: "30 minutes",
    dietaryRestrictions: ["Contains soy", "Contains beef"],
    description:
      "A quick Asian-inspired dish with tender beef and crisp vegetables in a savory sauce. Versatile and easily customizable.",
    rating: 4,
    foodId : "food6",
    addedToFav : false,

  },
  {
    name: "Margarita Pizza",
    ingredients: [
      "pizza dough",
      "tomato sauce",
      "fresh mozzarella cheese",
      "basil leaves",
      "olive oil",
      "salt",
    ],
    processToPrepare: [
      "Preheat oven to 450°F (230°C).",
      "Roll out pizza dough into a circle on a floured surface.",
      "Spread tomato sauce evenly over dough.",
      "Tear fresh mozzarella cheese into pieces and scatter over sauce.",
      "Drizzle with olive oil and sprinkle with salt.",
      "Bake for 10-12 minutes until crust is golden and cheese is bubbly.",
      "Top with fresh basil leaves before serving.",
    ],
    cuisine: "Italian",
    preparationTime: "25 minutes",
    dietaryRestrictions: ["Contains dairy", "Vegetarian"],
    description:
      "A classic Italian pizza with a thin crust, fresh tomato sauce, mozzarella, and basil. Simple ingredients showcasing authentic flavors.",
    rating: 5,
    foodId : "food7",
    addedToFav : false,

  },
  {
    name: "Greek Salad",
    ingredients: [
      "cucumbers",
      "tomatoes",
      "red onion",
      "feta cheese",
      "kalamata olives",
      "olive oil",
      "lemon juice",
      "oregano",
    ],
    processToPrepare: [
      "Chop cucumbers, tomatoes, and red onion.",
      "Combine in a bowl with crumbled feta cheese and kalamata olives.",
      "Whisk together olive oil, lemon juice, and oregano for dressing.",
      "Toss salad with dressing just before serving.",
    ],
    cuisine: "Greek",
    preparationTime: "15 minutes",
    dietaryRestrictions: ["Contains dairy", "Vegetarian"],
    description:
      "A refreshing Mediterranean salad with crisp vegetables, tangy feta, and briny olives. Light yet satisfying, perfect for warm days.",
    rating: 4,
    foodId : "food8",
    addedToFav : false,

  },
  {
    name: "Pancakes",
    ingredients: [
      "flour",
      "milk",
      "eggs",
      "sugar",
      "baking powder",
      "butter",
      "maple syrup",
    ],
    processToPrepare: [
      "Whisk together flour, sugar, baking powder, and a pinch of salt in a bowl.",
      "In another bowl, whisk together milk, eggs, and melted butter.",
      "Combine wet and dry ingredients until just mixed (don't overmix).",
      "Heat a griddle or skillet over medium heat and grease lightly.",
      "Pour batter onto griddle to form pancakes.",
      "Cook until bubbles form on the surface, then flip and cook until golden brown.",
      "Serve hot with maple syrup.",
    ],
    cuisine: "American",
    preparationTime: "20 minutes",
    dietaryRestrictions: ["Contains dairy", "Contains eggs"],
    description:
      "Fluffy, golden-brown breakfast staple loved worldwide. Versatile and comforting, perfect with maple syrup or various toppings.",
    rating: 3,
    foodId : "food9",
    addedToFav : false,
   
  },
  {
    name: "Sushi Rolls",
    ingredients: [
      "sushi rice",
      "nori seaweed sheets",
      "sashimi-grade fish (tuna, salmon)",
      "avocado",
      "cucumber",
      "soy sauce",
      "wasabi",
    ],
    processToPrepare: [
      "Cook sushi rice according to package instructions and let cool.",
      "Place nori seaweed sheet on a bamboo sushi mat.",
      "Spread rice evenly over nori, leaving a 1-inch border at the top.",
      "Arrange sliced fish, avocado, and cucumber in a line across the center of the rice.",
      "Roll the sushi tightly using the bamboo mat, sealing the edge with a bit of water.",
      "Slice into rounds using a sharp knife.",
      "Serve with soy sauce and wasabi.",
    ],
    cuisine: "Japanese",
    preparationTime: "45 minutes",
    dietaryRestrictions: ["Contains raw fish", "Contains soy"],
    description:
      "Japanese delicacy featuring vinegared rice, fresh fish, and vegetables rolled in seaweed. A harmonious blend of flavors and textures.",
    rating: 5,
    foodId : "food10",
    addedToFav : false,
  },
  {
    name: "Hamburger",
    ingredients: [
      "ground beef",
      "burger buns",
      "lettuce",
      "tomato slices",
      "onion slices",
      "pickles",
      "cheese slices",
      "ketchup",
      "mustard",
    ],
    processToPrepare: [
      "Form ground beef into patties and season with salt and pepper.",
      "Grill or pan-fry patties until cooked to desired doneness.",
      "Toast burger buns on the grill or in a toaster.",
      "Assemble burgers with lettuce, tomato slices, onion slices, pickles, cheese slices, ketchup, and mustard.",
      "Serve hot.",
    ],
    cuisine: "American",
    preparationTime: "20 minutes",
    dietaryRestrictions: ["Contains dairy", "Contains beef"],
    description:
      "Iconic American sandwich with a juicy beef patty and various toppings in a soft bun. Customizable and satisfying.",
    rating: 4,
    foodId : "food11",
    addedToFav : false,
  },
  {
    name: "Pasta Primavera",
    ingredients: [
      "pasta (penne or spaghetti)",
      "assorted vegetables (bell peppers, zucchini, cherry tomatoes)",
      "garlic",
      "olive oil",
      "parmesan cheese",
      "fresh herbs (basil, parsley)",
      "lemon juice",
    ],
    processToPrepare: [
      "Cook pasta according to package instructions.",
      "Sauté garlic in olive oil until fragrant.",
      "Add assorted vegetables and cook until tender-crisp.",
      "Toss cooked pasta with vegetables, parmesan cheese, fresh herbs, and lemon juice.",
      "Season with salt and pepper to taste.",
      "Serve warm.",
    ],
    cuisine: "Italian-American",
    preparationTime: "25 minutes",
    dietaryRestrictions: ["Contains dairy", "Vegetarian"],
    description:
      "Light Italian-American pasta dish packed with colorful vegetables and fresh herbs. A celebration of seasonal produce.",
    rating: 4,
    foodId : "food12",
    addedToFav : false,
  },
  {
    name: "Guacamole",
    ingredients: [
      "avocados",
      "lime juice",
      "red onion",
      "tomato",
      "cilantro",
      "jalapeno (optional)",
      "salt",
    ],
    processToPrepare: [
      "Cut avocados in half and remove pits.",
      "Scoop avocado flesh into a bowl and mash with a fork.",
      "Stir in lime juice to prevent browning.",
      "Mix in finely chopped red onion, diced tomato, chopped cilantro, and minced jalapeno (if using).",
      "Season with salt to taste.",
      "Serve immediately with tortilla chips.",
    ],
    cuisine: "Mexican",
    preparationTime: "15 minutes",
    dietaryRestrictions: ["Vegan", "Gluten-free"],
    description:
      "Creamy Mexican dip made with ripe avocados, lime juice, and fresh vegetables. Perfect as a snack or condiment.",
    rating: 5,
    foodId : "food13",
    addedToFav : false,
  },
  {
    name: "BBQ Ribs",
    ingredients: [
      "pork ribs",
      "barbecue sauce",
      "salt",
      "pepper",
      "garlic powder",
      "onion powder",
      "paprika",
    ],
    processToPrepare: [
      "Preheat oven to 300°F (150°C).",
      "Rub ribs with salt, pepper, garlic powder, onion powder, and paprika.",
      "Wrap ribs tightly in aluminum foil and bake for 2.5 to 3 hours until tender.",
      "Remove from foil and brush generously with barbecue sauce.",
      "Grill over medium-high heat for 10-15 minutes, brushing with more sauce.",
      "Serve hot.",
    ],
    cuisine: "American",
    preparationTime: "3 hours",
    dietaryRestrictions: [],
    description:
      "Tender pork ribs coated in a savory barbecue sauce. Slow-baked to perfection, then grilled for a caramelized finish.",
    rating: 4,
    foodId : "food14",
    addedToFav : false,
  },
];

export let ingridents = [
  "spaghetti",
  "pancetta",
  "egg yolks",
  "parmesan cheese",
  "black pepper",
  "chicken thighs",
  "yogurt",
  "tomato sauce",
  "cream",
  "spices",
  "romaine lettuce",
  "croutons",
  "Caesar dressing",
  "lemon juice",
  "olive oil",
  "anchovy paste",
  "ground beef",
  "taco seasoning",
  "tortillas",
  "lettuce",
  "tomatoes",
  "cheese",
  "sour cream",
  "flour",
  "butter",
  "sugar",
  "brown sugar",
  "eggs",
  "vanilla extract",
  "chocolate chips",
  "baking soda",
  "fresh mozzarella cheese",
  "basil leaves",
  "balsamic vinegar",
  "salt",
  "beef sirloin",
  "soy sauce",
  "ginger",
  "garlic",
  "vegetables",
  "sesame oil",
  "pizza dough",
  "cucumbers",
  "red onion",
  "feta cheese",
  "kalamata olives",
  "oregano",
  "milk",
  "baking powder",
  "maple syrup",
  "sushi rice",
  "nori seaweed sheets",
  "sashimi-grade fish",
  "avocado",
  "cucumber",
  "wasabi",
  "burger buns",
  "onion slices",
  "pickles",
  "ketchup",
  "mustard",
  "pasta",
  "fresh herbs",
  "lime juice",
  "cilantro",
  "jalapeno",
];

export let cuisine = [
  "Italian",
  "Indian",
  "Italian-American",
  "Mexican",
  "American",
  "Asian",
  "Greek",
  "Japanese",
];

export let time = [
  "30 minutes",
  "1 hour 30 minutes",
  "15 minutes",
  "25 minutes",
  "10 minutes",
  "20 minutes",
  "45 minutes",
];

export let Restrictions = [
  "Contains dairy",
  "Contains eggs",
  "Contains pork",
  "Contains fish",
  "Contains beef",
  "Vegetarian",
  "Contains soy",
  "Contains raw fish",
  "Vegan",
  "Gluten-free",
];
